import { diffLines, diffWords, diffChars, Change } from "diff";
import type { TextDiffGranularity } from "./Stores/diffCheckerStore";

export function generateTextDiffReport(
  original: string,
  modified: string,
  granularity: TextDiffGranularity,
): string {
  // ✅ replace with
  let changes: Change[];
  if (granularity === "lines") {
    changes = diffLines(original, modified);
  } else if (granularity === "words") {
    changes = diffWords(original, modified);
  } else {
    changes = diffChars(original, modified);
  }

  const added = changes
    .filter((c) => c.added)
    .reduce((a, c) => a + (c.count ?? 0), 0);
  const removed = changes
    .filter((c) => c.removed)
    .reduce((a, c) => a + (c.count ?? 0), 0);
  const unchanged = changes
    .filter((c) => !c.added && !c.removed)
    .reduce((a, c) => a + (c.count ?? 0), 0);

  const now = new Date().toLocaleString("en-IN", {
    dateStyle: "long",
    timeStyle: "short",
  });

  const lines: string[] = [
    "# Diff Checker Report",
    `> Generated: ${now}`,
    `> Source: Blackcurrant — Diff Checker`,
    `> Granularity: ${granularity}`,
    "",
    "---",
    "",
    "## Summary",
    "",
    `- **Added:** ${added} ${granularity}`,
    `- **Removed:** ${removed} ${granularity}`,
    `- **Unchanged:** ${unchanged} ${granularity}`,
    `- **Total changes:** ${added + removed}`,
    "",
    "---",
    "",
    "## Diff",
    "",
    "```diff",
  ];

  changes.forEach((change) => {
    const prefix = change.added ? "+" : change.removed ? "-" : " ";
    const text = change.value.replace(/\n$/, "");
    text.split("\n").forEach((line) => {
      lines.push(`${prefix} ${line}`);
    });
  });

  lines.push("```");
  lines.push("");
  lines.push("---");
  lines.push("_Report generated by Blackcurrant — Diff Checker_");

  return lines.join("\n");
}

export function triggerTextReportDownload(
  original: string,
  modified: string,
  granularity: TextDiffGranularity,
): void {
  const md = generateTextDiffReport(original, modified, granularity);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  const ts = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  a.href = url;
  a.download = `diff-report-${ts}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

export function triggerImageDiffDownload(canvas: HTMLCanvasElement): void {
  const ts = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  canvas.toBlob((blob) => {
    if (!blob) return;
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `image-diff-${ts}.png`;
    a.click();
    URL.revokeObjectURL(url);
  }, "image/png");
}
